version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./php
      dockerfile: Dockerfile
    image: my-app
    container_name: my-app
    restart: unless-stopped
    working_dir: /var/www/
    command: sh -c  "composer install && php artisan key:generate && php artisan migrate"
    volumes:
      - ./:/var/www
    networks:
      - my-app

  db:
    image: mysql:8.0
    container_name: my-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - ./mysql/:/docker-entrypoint-initdb.d
    networks:
      - my-app

  nginx:
    image: nginx:alpine
    container_name: my-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - my-app

networks:
  my-app:
    driver: bridge